echo "Cleaning LaTeX compilation files ..."
rm thesis.aux; echo "Removing thesis.aux"
rm thesis.bbl; echo "Removing thesis.bbl"
rm thesis.blg; echo "Removing thesis.blg"
rm thesis.brf; echo "Removing thesis.brf"
rm thesis.dvi; echo "Removing thesis.dvi"
rm thesis.fls; echo "Removing thesis.fls"
rm thesis.log; echo "Removing thesis.log"
rm thesis.out; echo "Removing thesis.out"
rm thesis.toc; echo "Removing thesis.toc"
rm thesis.lot; echo "Removing thesis.lot"
rm thesis.lof; echo "Removing thesis.lof"
rm thesis.fdb_latexmk; echo "Removing thesis.fdb_latexmk"
echo "-- Done."
